//go:build ignore

// gen_selfaudit.go regenerates selfaudit/manifest_generated.go: a
// build-time snapshot of (1) every import path Go's own `go list std`
// considers part of the standard library, and (2) bareport's own
// fully-walked import graph (`go list -deps .`), plus a few facts read
// straight from go.mod.
//
// Why build time, not runtime: `--verify-zero-dep`'s whole point is
// that the *shipped binary* can prove the zero-dependency claim about
// itself. Two designs were possible — shell out to `go list` at
// runtime, or capture the same data once at build/generate time and
// embed it. Runtime shelling out was rejected on purpose: it would
// mean the binary needs the Go toolchain installed just to run its own
// self-check (breaking the "single compiled artifact, nothing else
// needed" story every other part of this README leans on), and it
// would make `--verify-zero-dep` the first and only place `os/exec`
// appears in the shipped binary (see integration/main.go's doc comment
// — today that's the *only* place os/exec appears, and deliberately
// stays that way). This generator is the one place `go list` actually
// runs — as a `go:build ignore`d, never-shipped source file, the same
// pattern demo-targets/*.go already uses for standalone helper
// programs excluded from the real build.
//
// Regenerate after any change to bareport's own import graph:
//
//	go run tools/gen_selfaudit.go
//
// or:
//
//	make selfaudit-manifest
//
// The Makefile's own `build` target does NOT run this automatically —
// regenerating requires the Go toolchain (`go list`), which is exactly
// the runtime dependency this design avoids baking into the shipped
// binary. If you add or remove an import anywhere in bareport, rerun
// this by hand (or via `make selfaudit-manifest`) before building, or
// `--verify-zero-dep` will be checking a stale snapshot.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"sort"
	"strconv"
	"strings"
	"time"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen_selfaudit:", err)
		os.Exit(1)
	}
}

func run() error {
	modulePath, goDirective, requireLines, err := readGoMod("go.mod")
	if err != nil {
		return fmt.Errorf("reading go.mod: %w", err)
	}

	stdlib, err := goListLines("list", "std")
	if err != nil {
		return fmt.Errorf("go list std: %w", err)
	}
	sort.Strings(stdlib)

	ownImports, err := goListLines("list", "-deps", ".")
	if err != nil {
		return fmt.Errorf("go list -deps .: %w", err)
	}
	sort.Strings(ownImports)

	goVersion, err := goListLines("env", "GOVERSION")
	if err != nil {
		return fmt.Errorf("go env GOVERSION: %w", err)
	}
	gv := "unknown"
	if len(goVersion) == 1 {
		gv = goVersion[0]
	}

	f, err := os.Create("selfaudit/manifest_generated.go")
	if err != nil {
		return err
	}
	defer f.Close()

	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)
	fmt.Fprintf(w, "// Code generated by tools/gen_selfaudit.go via `make selfaudit-manifest`. DO NOT EDIT.\n")
	fmt.Fprintf(w, "// Regenerate with: go run tools/gen_selfaudit.go  (or: make selfaudit-manifest)\n")
	fmt.Fprintf(w, "//\n")
	fmt.Fprintf(w, "// Captured at generate time, %s, using %s.\n", time.Now().UTC().Format(time.RFC3339), gv)
	fmt.Fprintf(w, "// See selfaudit.go and tools/gen_selfaudit.go's doc comment for what this\n")
	fmt.Fprintf(w, "// data is and why it's a build-time snapshot rather than a runtime `go\n")
	fmt.Fprintf(w, "// list` call.\n")
	fmt.Fprintf(w, "package selfaudit\n\n")

	fmt.Fprintf(w, "// ModulePath, GoDirective, RequireLineCount: read from go.mod at generate time.\n")
	fmt.Fprintf(w, "const (\n")
	fmt.Fprintf(w, "\tModulePath       = %q\n", modulePath)
	fmt.Fprintf(w, "\tGoDirective      = %q\n", goDirective)
	fmt.Fprintf(w, "\tRequireLineCount = %d\n", requireLines)
	fmt.Fprintf(w, "\tGeneratedWithGo  = %q\n", gv)
	fmt.Fprintf(w, ")\n\n")

	fmt.Fprintf(w, "// ownImports: bareport's own fully-walked import graph at generate time\n")
	fmt.Fprintf(w, "// (`go list -deps .`, %d entries) — this IS the import graph\n", len(ownImports))
	fmt.Fprintf(w, "// `--verify-zero-dep` reports on; it is not re-walked at runtime.\n")
	writeStringSlice(w, "ownImports", ownImports)

	if err := w.Flush(); err != nil {
		return err
	}

	// Run the generated source through go/format (stdlib — the same
	// formatter gofmt itself is built on) before writing, so `gofmt
	// -l .` stays clean on generated output without needing to shell
	// out to the `gofmt` binary specifically.
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting generated source: %w", err)
	}
	if _, err := f.Write(formatted); err != nil {
		return err
	}

	// stdlibPackages, separately: a plain-text data file (one import
	// path per line), embedded via go:embed in selfaudit.go rather
	// than baked into manifest_generated.go as a Go literal like
	// ownImports above. Two reasons to split it out: go:embed is
	// itself worth demonstrating directly (see README's
	// --verify-zero-dep write-up, which specifically calls out
	// go:embed for this table), and a flat one-per-line text file is
	// the more natural shape for "the real go list std output,
	// unmodified" than reformatting it into Go syntax would be.
	stdlibFile, err := os.Create("selfaudit/stdlib_packages.txt")
	if err != nil {
		return err
	}
	defer stdlibFile.Close()
	sw := bufio.NewWriter(stdlibFile)
	for _, p := range stdlib {
		fmt.Fprintln(sw, p)
	}
	return sw.Flush()
}

func writeStringSlice(w *bufio.Writer, name string, items []string) {
	fmt.Fprintf(w, "var %s = []string{\n", name)
	for _, s := range items {
		fmt.Fprintf(w, "\t%q,\n", s)
	}
	fmt.Fprintf(w, "}\n\n")
}

// goListLines runs `go <args...>` and returns stdout split into
// trimmed, non-empty lines.
func goListLines(args ...string) ([]string, error) {
	cmd := exec.Command("go", args...)
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("go %s: %w", strings.Join(args, " "), err)
	}
	var lines []string
	for _, l := range strings.Split(string(out), "\n") {
		l = strings.TrimSpace(l)
		if l != "" {
			lines = append(lines, l)
		}
	}
	return lines, nil
}

// readGoMod hand-parses the two lines gen_selfaudit.go needs
// (`module ...` and `go ...`) plus a require-line count, rather than
// pulling in golang.org/x/mod/modfile — go.mod's format is simple
// enough (whitespace-trimmed, one directive per line for the cases
// this tool cares about) that a full module-file parser would be more
// machinery than the two facts here justify, and this generator is
// itself excluded from the shipped binary either way.
func readGoMod(path string) (modulePath, goDirective string, requireLines int, err error) {
	f, err := os.Open(path)
	if err != nil {
		return "", "", 0, err
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		switch {
		case strings.HasPrefix(line, "module "):
			modulePath = strings.TrimSpace(strings.TrimPrefix(line, "module"))
		case strings.HasPrefix(line, "go "):
			goDirective = strings.TrimSpace(strings.TrimPrefix(line, "go"))
		case strings.HasPrefix(line, "require "), line == "require (":
			requireLines++
		}
	}
	if err := sc.Err(); err != nil {
		return "", "", 0, err
	}
	if modulePath == "" {
		return "", "", 0, fmt.Errorf("no module line found in %s", path)
	}
	// Sanity check the go directive parses as a version-ish string;
	// not stored beyond that, just fails loudly if go.mod's shape
	// ever changes in a way this simple parser can't handle.
	if _, verr := strconv.ParseFloat(strings.SplitN(goDirective, ".", 2)[0], 64); verr != nil && goDirective != "" {
		return "", "", 0, fmt.Errorf("unexpected go directive shape: %q", goDirective)
	}
	return modulePath, goDirective, requireLines, nil
}
